-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 15:45:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stampee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stampee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stampee` DEFAULT CHARACTER SET utf8 ;
USE `stampee` ;

-- -----------------------------------------------------
-- Table `stampee`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`role` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`utilisateur` (
  `uti_id` INT NOT NULL AUTO_INCREMENT,
  `uti_prenom` VARCHAR(45) NOT NULL,
  `uti_nom` VARCHAR(45) NOT NULL,
  `uti_courriel` VARCHAR(255) NOT NULL,
  `uti_mdp` VARCHAR(255) NOT NULL,
  `uti_dateInscription` VARCHAR(45) NOT NULL,
  `uti_confirmation` VARCHAR(30) NOT NULL,
  `uti_rol_id_ce` INT NOT NULL,
  PRIMARY KEY (`uti_id`, `uti_rol_id_ce`),
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`uti_rol_id_ce`)
    REFERENCES `stampee`.`role` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_role1_idx` ON `stampee`.`utilisateur` (`uti_rol_id_ce` ASC);


-- -----------------------------------------------------
-- Table `stampee`.`enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`enchere` (
  `enc_id` INT NOT NULL AUTO_INCREMENT,
  `enc_estimation` DECIMAL NOT NULL,
  `enc_dateDebut` DATETIME NOT NULL,
  `enc_dateFin` DATETIME NOT NULL,
  `enc_prixPlancher` DECIMAL NOT NULL,
  `enc_nombreDeMise` INT NULL,
  `enc_coupDeCoeur` TINYINT NULL,
  PRIMARY KEY (`enc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`categorie` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`pays` (
  `pay_id` INT NOT NULL  AUTO_INCREMENT,
  `pay_nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pay_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stampee`.`timbre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`timbre` (
  `tim_id` INT NOT NULL AUTO_INCREMENT,
  `tim_nom` VARCHAR(45) NOT NULL,
  `tim_description` VARCHAR(200) NULL,
  `tim_dateDeCreation` DATETIME NOT NULL,
  `tim_couleurs` VARCHAR(100) NOT NULL,
  `tim_condition` ENUM("Parfaite", "Excellente", "Bonne", "Moyenne", "Endommagé") NOT NULL,
  `tim_tirage` INT NULL,
  `tim_dimensions` VARCHAR(45) NULL,
  `tim_certification` TINYINT NULL,
  `tim_enc_id_ce` INT NOT NULL,
  `tim_cat_id_ce` INT NOT NULL,
  `tim_pay_id_ce` INT NOT NULL,
  PRIMARY KEY (`tim_id`, `tim_enc_id_ce`),
  CONSTRAINT `fk_timbre_enchere1`
    FOREIGN KEY (`tim_enc_id_ce`)
    REFERENCES `stampee`.`enchere` (`enc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timbre_categorie1`
    FOREIGN KEY (`tim_cat_id_ce`)
    REFERENCES `stampee`.`categorie` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timbre_pays1`
    FOREIGN KEY (`tim_pay_id_ce`)
    REFERENCES `stampee`.`pays` (`pay_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_timbre_enchere1_idx` ON `stampee`.`timbre` (`tim_enc_id_ce` ASC);

CREATE INDEX `fk_timbre_categorie1_idx` ON `stampee`.`timbre` (`tim_cat_id_ce` ASC);

CREATE INDEX `fk_timbre_pays1_idx` ON `stampee`.`timbre` (`tim_pay_id_ce` ASC);


-- -----------------------------------------------------
-- Table `stampee`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`favoris` (
  `fav_uti_id_ce` INT NOT NULL,
  `fav_enc_id_ce` INT NOT NULL,
  PRIMARY KEY (`fav_uti_id_ce`, `fav_enc_id_ce`),
  CONSTRAINT `fk_utilisateur_has_enchere_utilisateur`
    FOREIGN KEY (`fav_uti_id_ce`)
    REFERENCES `stampee`.`utilisateur` (`uti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_enchere_enchere1`
    FOREIGN KEY (`fav_enc_id_ce`)
    REFERENCES `stampee`.`enchere` (`enc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_has_enchere_enchere1_idx` ON `stampee`.`favoris` (`fav_enc_id_ce` ASC);

CREATE INDEX `fk_utilisateur_has_enchere_utilisateur_idx` ON `stampee`.`favoris` (`fav_uti_id_ce` ASC);


-- -----------------------------------------------------
-- Table `stampee`.`mise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`mise` (
  `mis_uti_id_ce` INT NOT NULL,
  `mis_enc_id_ce` INT NOT NULL,
  `mis_miseActuelle` DECIMAL NULL,
  PRIMARY KEY (`mis_uti_id_ce`, `mis_enc_id_ce`),
  CONSTRAINT `fk_utilisateur_has_enchere_utilisateur1`
    FOREIGN KEY (`mis_uti_id_ce`)
    REFERENCES `stampee`.`utilisateur` (`uti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_enchere_enchere2`
    FOREIGN KEY (`mis_enc_id_ce`)
    REFERENCES `stampee`.`enchere` (`enc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_utilisateur_has_enchere_enchere2_idx` ON `stampee`.`mise` (`mis_enc_id_ce` ASC);

CREATE INDEX `fk_utilisateur_has_enchere_utilisateur1_idx` ON `stampee`.`mise` (`mis_uti_id_ce` ASC);


-- -----------------------------------------------------
-- Table `stampee`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee`.`image` (
  `img_id` INT NOT NULL AUTO_INCREMENT,
  `img_nom` VARCHAR(45) NOT NULL,
  `img_tim_id_ce` INT NOT NULL,
  PRIMARY KEY (`img_id`, `img_tim_id_ce`),
  CONSTRAINT `fk_image_timbre1`
    FOREIGN KEY (`img_tim_id_ce`)
    REFERENCES `stampee`.`timbre` (`tim_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_image_timbre1_idx` ON `stampee`.`image` (`img_tim_id_ce` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
